// Flutter web bootstrap - generated by Flutter CLI
(function () {
  'use strict';

  const serviceWorkerVersion = null;

  let scriptLoaded = false;

  function loadMainDartJs() {
    if (scriptLoaded) return;
    scriptLoaded = true;

    const appRunner = '_flutter.loader.load';

    if (typeof appRunner === 'function') {
      appRunner();
    } else {
      const scriptTag = document.createElement('script');
      scriptTag.src = 'main.dart.js';
      scriptTag.type = 'application/javascript';
      document.body.appendChild(scriptTag);
    }
  }

  // PWA service worker
  if ('serviceWorker' in navigator) {
    window.addEventListener('load', function () {
      navigator.serviceWorker.register('/flutter_service_worker.js');
    });
  }

  // Auto-load
  if (document.readyState === 'complete') {
    loadMainDartJs();
  } else {
    document.addEventListener('readystatechange', () => {
      if (document.readyState === 'complete') {
        loadMainDartJs();
      }
    });
  }
})();
